networks:
  nsse-network:
    driver: bridge
    name: nsse-network

services:

  nsse.terraform-init.internal:
    container_name: nsse.terraform-init.internal
    depends_on:
      - nsse.localstack.internal
    image: hashicorp/terraform:light
    command: ["init"]
    working_dir: ${TERRAFORM_CONTAINER_PATH}
    networks:
      - nsse-network
    volumes:
      - ${TERRAFORM_HOST_PATH}:${TERRAFORM_CONTAINER_PATH}

  nsse.terraform-apply.internal:
    container_name: nsse.terraform-apply.internal
    depends_on:
      - nsse.terraform-init.internal
    image: hashicorp/terraform:light
    command: ["apply", "-auto-approve"]
    working_dir: ${TERRAFORM_CONTAINER_PATH}
    networks:
      - nsse-network
    volumes:
      - ${TERRAFORM_HOST_PATH}:${TERRAFORM_CONTAINER_PATH}

  nsse.localstack.internal:
    container_name: nsse.localstack.internal
    image: localstack/localstack
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
    networks:
      - nsse-network

  nsse.nginx.internal:
    container_name: nsse.nginx.internal
    image: nginx:1.25.2-alpine
    ports:
      - 44300:44300
    volumes:
      - ${NGINX_CONF_HOST_PATH}:${NGINX_CONF_CONTAINER_PATH}
      - ${NGINX_CERT_HOST_PATH}:${NGINX_CERT_CONTAINER_PATH}
      - ${NGINX_KEY_HOST_PATH}:${NGINX_KEY_CONTAINER_PATH}
    networks:
      - nsse-network

  nsse.database.internal:
    container_name: nsse.database.internal
    image: postgres:16.0-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - nsse-network